elec_cart:
    resource: "@ElecBundle/Resources/config/routing/cart.yml"
    prefix:   /admin/cart

elec_homepage_admin:
    path:     /admin
    defaults: { _controller: ElecBundle:Default:backEnd }

elec_cartitem:
    resource: "@ElecBundle/Resources/config/routing/cartitem.yml"
    prefix:   /admin/cartitem

elec_category:
    resource: "@ElecBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

elec_orderinfo:
    resource: "@ElecBundle/Resources/config/routing/orderinfo.yml"
    prefix:   /admin/orderinfo

elec_orderitem:
    resource: "@ElecBundle/Resources/config/routing/orderitem.yml"
    prefix:   /admin/orderitem

elec_product:
    resource: "@ElecBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

elec_subcategory:
    resource: "@ElecBundle/Resources/config/routing/subcategory.yml"
    prefix:   /admin/subcategory

elec_user:
    resource: "@ElecBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

elec_homepage:
    path:     /
    defaults: { _controller: ElecBundle:Default:index }

elec_profile:
    resource: "@ElecBundle/Resources/config/routing/profile.yml"
    prefix:   /admin/profile

elec_homepage_cart:
    path:     /cart
    defaults: { _controller: ElecBundle:Default:cart }

elec_homepage_cart_new:
    path:     /cart/new/{id}
    defaults: { _controller: ElecBundle:Default:addToCart }

elec_homepage_cart_delete:
    path:     /cart/delete/{id}
    defaults: { _controller: "ElecBundle:Default:deleteFromCart" }