elec_cart:
    resource: "@ElecBundle/Resources/config/routing/cart.yml"
    prefix:   /cart

elec_homepage:
    path:     /
    defaults: { _controller: ElecBundle:Default:index }

elec_cartitem:
    resource: "@ElecBundle/Resources/config/routing/cartitem.yml"
    prefix:   /cartitem

elec_category:
    resource: "@ElecBundle/Resources/config/routing/category.yml"
    prefix:   /category

elec_orderinfo:
    resource: "@ElecBundle/Resources/config/routing/orderinfo.yml"
    prefix:   /orderinfo

elec_orderitem:
    resource: "@ElecBundle/Resources/config/routing/orderitem.yml"
    prefix:   /orderitem

elec_product:
    resource: "@ElecBundle/Resources/config/routing/product.yml"
    prefix:   /product

elec_subcategory:
    resource: "@ElecBundle/Resources/config/routing/subcategory.yml"
    prefix:   /subcategory