ElecBundle\Entity\CartItem:
    type: entity
    table: null
    repositoryClass: ElecBundle\Repository\CartItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        unitPrice:
            type: float
            length: 11
        quantity:
            type: integer
            length: 11
    manyToOne:
        cart:
            targetEntity: Cart
            inversedBy: cartItems
            joinColumn:
                name: cart_id
                referencedColumnName: id
    oneToOne:
        product:
            targetEntity: Product
            inversedBy: cartItem
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }