ElecBundle\Entity\Profile:
    type: entity
    table: null
    repositoryClass: ElecBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phonenumber:
            type: string
            length: 255
            nullable: true
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
        nation:
            type: string
            length: 255
            nullable: true
        adress:
            type: string
            length: 255
            nullable: true
        companyname:
            type: string
            length: 255
            nullable: true
        businessMode:
            type: string
            length: 255
            nullable: true
    oneToOne:
        user:
            targetEntity: User
            inversedBy: profile
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }