profile_index:
    path:     /
    defaults: { _controller: "ElecBundle:Profile:index" }
    methods:  GET

profile_show:
    path:     /{id}/show
    defaults: { _controller: "ElecBundle:Profile:show" }
    methods:  GET

profile_new:
    path:     /new
    defaults: { _controller: "ElecBundle:Profile:new" }
    methods:  [GET, POST]

profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElecBundle:Profile:edit" }
    methods:  [GET, POST]

profile_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElecBundle:Profile:delete" }
    methods:  DELETE
