subcategory_index:
    path:     /
    defaults: { _controller: "ElecBundle:SubCategory:index" }
    methods:  GET

subcategory_show:
    path:     /{id}/show
    defaults: { _controller: "ElecBundle:SubCategory:show" }
    methods:  GET

subcategory_new:
    path:     /new
    defaults: { _controller: "ElecBundle:SubCategory:new" }
    methods:  [GET, POST]

subcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElecBundle:SubCategory:edit" }
    methods:  [GET, POST]

subcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElecBundle:SubCategory:delete" }
    methods:  DELETE
